# coding: utf-8

"""
    Krak REST API

    Krak REST API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.core_photos_data import CorePhotosData  # noqa: E501
from openapi_client.rest import ApiException

class TestCorePhotosData(unittest.TestCase):
    """CorePhotosData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CorePhotosData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.core_photos_data.CorePhotosData()  # noqa: E501
        if include_optional :
            return CorePhotosData(
                depth_from = 1.337, 
                depth_to = 1.337
            )
        else :
            return CorePhotosData(
                depth_from = 1.337,
                depth_to = 1.337,
        )

    def testCorePhotosData(self):
        """Test CorePhotosData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
