# coding: utf-8

"""
    Krak REST API

    Krak REST API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.boreholes_api import BoreholesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestBoreholesApi(unittest.TestCase):
    """BoreholesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.boreholes_api.BoreholesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_boreholes_create(self):
        """Test case for boreholes_create

        Create a new borehole  # noqa: E501
        """
        pass

    def test_boreholes_delete(self):
        """Test case for boreholes_delete

        Delete a borehole  # noqa: E501
        """
        pass

    def test_boreholes_read_all(self):
        """Test case for boreholes_read_all

        Read all boreholes in db, sorted by id  # noqa: E501
        """
        pass

    def test_boreholes_read_one(self):
        """Test case for boreholes_read_one

        Read one borehole  # noqa: E501
        """
        pass

    def test_boreholes_update(self):
        """Test case for boreholes_update

        Update a borehole  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
