# coding: utf-8

"""
    Krak REST API

    Krak REST API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.core_photo_output_all_of import CorePhotoOutputAllOf  # noqa: E501
from openapi_client.rest import ApiException

class TestCorePhotoOutputAllOf(unittest.TestCase):
    """CorePhotoOutputAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CorePhotoOutputAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.core_photo_output_all_of.CorePhotoOutputAllOf()  # noqa: E501
        if include_optional :
            return CorePhotoOutputAllOf(
                core_photo_id = 56
            )
        else :
            return CorePhotoOutputAllOf(
        )

    def testCorePhotoOutputAllOf(self):
        """Test CorePhotoOutputAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
