# coding: utf-8

"""
    Krak REST API

    Krak REST API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.core_photos_api import CorePhotosApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCorePhotosApi(unittest.TestCase):
    """CorePhotosApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.core_photos_api.CorePhotosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_core_photo_create(self):
        """Test case for core_photo_create

        Create a new core photo  # noqa: E501
        """
        pass

    def test_core_photo_read_all(self):
        """Test case for core_photo_read_all

        Read all core photo ids in db, sorted by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
