# coding: utf-8

# flake8: noqa
"""
    Krak REST API

    Krak REST API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.boreholes import Boreholes
from openapi_client.models.core_photos import CorePhotos
from openapi_client.models.core_photos_data import CorePhotosData
