# coding: utf-8

"""
    Krak REST API

    Krak REST API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class CorePhotosData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'depth_from': 'float',
        'depth_to': 'float'
    }

    attribute_map = {
        'depth_from': 'depth_from',
        'depth_to': 'depth_to'
    }

    def __init__(self, depth_from=None, depth_to=None, local_vars_configuration=None):  # noqa: E501
        """CorePhotosData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._depth_from = None
        self._depth_to = None
        self.discriminator = None

        self.depth_from = depth_from
        self.depth_to = depth_to

    @property
    def depth_from(self):
        """Gets the depth_from of this CorePhotosData.  # noqa: E501


        :return: The depth_from of this CorePhotosData.  # noqa: E501
        :rtype: float
        """
        return self._depth_from

    @depth_from.setter
    def depth_from(self, depth_from):
        """Sets the depth_from of this CorePhotosData.


        :param depth_from: The depth_from of this CorePhotosData.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and depth_from is None:  # noqa: E501
            raise ValueError("Invalid value for `depth_from`, must not be `None`")  # noqa: E501

        self._depth_from = depth_from

    @property
    def depth_to(self):
        """Gets the depth_to of this CorePhotosData.  # noqa: E501


        :return: The depth_to of this CorePhotosData.  # noqa: E501
        :rtype: float
        """
        return self._depth_to

    @depth_to.setter
    def depth_to(self, depth_to):
        """Sets the depth_to of this CorePhotosData.


        :param depth_to: The depth_to of this CorePhotosData.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and depth_to is None:  # noqa: E501
            raise ValueError("Invalid value for `depth_to`, must not be `None`")  # noqa: E501

        self._depth_to = depth_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CorePhotosData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CorePhotosData):
            return True

        return self.to_dict() != other.to_dict()
