# coding: utf-8

# flake8: noqa

"""
    Krak REST API

    Krak REST API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.borehole_api import BoreholeApi
from openapi_client.api.core_photos_api import CorePhotosApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.borehole_input import BoreholeInput
from openapi_client.models.borehole_output import BoreholeOutput
from openapi_client.models.borehole_output_all_of import BoreholeOutputAllOf
from openapi_client.models.core_photo_input import CorePhotoInput
from openapi_client.models.core_photo_input_crop_corners import CorePhotoInputCropCorners
from openapi_client.models.core_photo_output import CorePhotoOutput
from openapi_client.models.core_photo_output_all_of import CorePhotoOutputAllOf

